<template>
	<div id="container">
		<div id="menu">
			<div v-if="!menu">
				<img
					style="cursor: pointer"
					src="../menu.png"
					width="50"
					v-on:click="menu = true"
				/>
			</div>
			<div v-if="menu" v-on:mouseleave="menu = false">
				<div v-on:click="fadeIn('introduction')">
					<h3>Introduction</h3>
				</div>
				<div v-on:click="fadeIn('about')">
					<h3>Acknowledgements</h3>
				</div>
			</div>
		</div>
		<transition name="fade">
			<div id="dimmer" v-if="dimmer === 'introduction'">
				<section>
					<div></div>
					<div><h1>Community Network Project</h1></div>
				</section>
				<section>
					<div id="title">
						<span>
							<h3>Introduction</h3>
						</span>
					</div>
					<div>
						<p>
							Community Network Project exhibition visualizes the
							friendship network of the Minerva Class 2019 cohort.
							You can explore the exhibition in the following
							ways:
						</p>
						<br />
						<ul>
							<li>
								Hover an individual node to track the change of
								its journey and its friendship composition.
							</li>
							<li>
								Compare and contrast how subsets of people from
								different regions connect by various reasons.
							</li>
							<li>
								Observe how the whole network evolves by time ⏱,
								location 🏡, and the encounter with class 2020
								🤝 over the past three years.
							</li>
						</ul>
						<br />
						<p>
							This exhibition presents the beauty and fluidity of
							human connections and sparks reflections on the
							well-being of our community. Have we embraced the
							diversity in the community? Have we created islands
							that exclude people? How did we divide and unite
							people? How can we take these insights to facilitate
							the inclusion and interactions between people while
							respecting their boundaries? With these questions in
							mind, let’s start exploring!
						</p>
					</div>
				</section>
				<div id="buttonContainer">
					<button v-on:click="fadeIntro" style="grid-column: 3">
						<h1 style="padding-right: 0">Explore</h1>
					</button>
				</div>
				<div id="cross" v-on:click="fadeIntro">
					<img src="../cross.png" width="40px" />
				</div>
			</div>
			<div id="dimmer" v-if="dimmer === 'about'">
				<section>
					<div></div>
					<div><h1>Community Network Project</h1></div>
				</section>
				<section>
					<div id="title">
						<span>
							<h3>Acknowledgements</h3>
						</span>
					</div>
					<div>
						<p>
							We want to thank all the Minerva students from class
							2019 and class 2020 who trusted us to keep their
							friendship data secure and confidential as they
							participated in this project.
						</p>
						<br />
						<p>
							This project was led by
							<a
href="https://twitter.com/xiaofanliang"
								>Xiaofan Liang</a
							>
							who started the project and persisted in collecting
							the necessary data during a three year period. She
							also performed the data analysis necessary to gain
							insights into the dynamics of the community.
						</p>
						<br />
						<p>
							Eli Sullivan and Nicolas Gort were instrumental
							throughout the process as they worked to improve the
							survey quality, aided data collection, and prepared
							the yearly reports.
						</p>
						<br />
						<p>
							Thanks to
							<a href="http://jskjott.com/">Jonathan Skjøtt</a>
							who designed this interactive website to provide a
							fun and engaging experience for people to explore
							the data generated by this project.
						</p>
					</div>
				</section>
				<div id="cross" v-on:click="fadeIntro">
					<img src="../cross.png" width="40px" />
				</div>
			</div>
		</transition>
	</div>
</template>

<script lang="ts">
import Vue from 'vue'

const menu = false

export default Vue.extend({
	name: 'introduction',
	props: ['dimmer'],
	data() {
		return {
			menu,
		}
	},
	methods: {
		fadeIntro: function() {
			this.$emit('clicked', { key: 'dimmer', input: false })
		},
		fadeIn: function(element: string) {
			this.$emit('clicked', { key: 'dimmer', input: element })
		},
	},
})
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
#container {
	position: absolute;
}

#dimmer {
	height: 100%;
	width: 100%;
	background-color: rgba(245, 245, 220, 0.9);
	padding-bottom: 2.5rem;
	position: fixed;
}

section {
	display: grid;
	grid-template-columns: 1fr 5fr 0.5fr;
	opacity: 1 !important;
	padding: 0rem 5rem 2.5rem 5rem;
	overflow-y: auto;
}

#buttonContainer {
	display: grid;
	grid-template-columns: 2fr 1fr 1fr 1fr 2fr;
	align-items: center;
	justify-items: center;
	opacity: 1 !important;
	padding: 2.5rem 5rem 0rem 5rem;
}

button {
	grid-column-start: 2;
	grid-column-end: 3;
	padding: 0.25rem 2rem 0.5rem 2rem;
	border-radius: 10px;
	stroke: 1rem;
	border-width: medium;
	border-color: black;
	background-color: rgba(245, 245, 220, 0.9);
	cursor: pointer;
}

.fade-enter-active,
.fade-leave-active {
	transition: opacity 0.5s;
}

.fade-enter,
.fade-leave-to
/* .fade-leave-active in <2.1.8 */

 {
	opacity: 0;
}

#cross {
	position: absolute;
	top: 0;
	right: 0;
	padding: 2rem 5rem 2rem 2rem;
	cursor: pointer;
}

#menu {
	position: absolute;
	margin: 2rem;
	padding: 0 2rem 2rem 0rem;
}

h3 {
	margin: 0 0 1rem 0;
}

h3:hover {
	cursor: pointer;
}
</style>
